### ISSUE TITLE
jsonresume.io is down

### ISSUE THREAD

**Issue by aslafy-z** [koddsson/jsonresume#31]
Is there any plan to make it back online? Thanks

**Comment by koddsson** [comment]
I think I forgot to pay my ~amazon~ heroku bill 😬

**Comment by koddsson** [comment]
You can use https://jsonresume.herokuapp.com/ in the meantime.

**Comment by koddsson** [comment]
Seems to be a DNS issue.

**Comment by koddsson** [comment]
This took a minute to figure out but I wasn't paying DNSSimple! 🙈 

Should be working now. Thank you for letting me know ✨
